const express = require('express');
const multer = require('multer');
const cors = require('cors');
const path = require('path');
const fs = require('fs');
const { v4: uuid } = require('uuid');
const archiver = require('archiver');
const { execFile } = require('child_process');
const { PDFDocument, degrees, rgb, StandardFonts } = require('pdf-lib');

const app = express();
const PORT = process.env.PORT || 10000;
const UP = path.join(__dirname, 'uploads');
const TMP = path.join(__dirname, 'tmp');
[UP, TMP].forEach(d => fs.mkdirSync(d, { recursive: true }));
app.disable('x-powered-by');
app.set('trust proxy', 1);
app.use(cors());
app.use(express.static(path.join(__dirname, 'public')));
app.use(express.json({ limit: '2mb' }));
const ALLOWED_EXT=new Set(['.pdf','.doc','.docx','.xls','.xlsx','.ppt','.pptx','.odt','.jpg','.jpeg','.png','.webp','.gif','.bmp','.tif','.tiff']);
const upload=multer({storage:multer.diskStorage({destination:(r,f,c)=>c(null,UP),filename:(r,f,c)=>c(null,uuid()+path.extname(f.originalname||'').toLowerCase())}),limits:{fileSize:200*1024*1024,files:50,fields:20,parts:70},fileFilter:(r,f,c)=>ALLOWED_EXT.has(path.extname(f.originalname||'').toLowerCase())?c(null,true):c(new Error('Tipo de arquivo não permitido.'))});
function run(cmd,args,options={}){return new Promise((resolve,reject)=>execFile(cmd,args,{maxBuffer:20*1024*1024,timeout:options.timeout||180000,windowsHide:true},(e,o,s)=>e?reject(new Error(String(s||e.message).slice(0,2500))):resolve(o)));}
function cleanup(...files){files.filter(Boolean).forEach(f=>fs.rm(f,{recursive:true,force:true},()=>{}));}
function validatePdf(f){if(!f)throw new Error('Nenhum arquivo foi enviado.');if(path.extname(f.originalname||'').toLowerCase()!=='.pdf')throw new Error('Este recurso aceita somente PDF.');}
function safeFileId(id){const n=path.basename(String(id||''));if(!/^[0-9a-f-]{36}\.pdf$/i.test(n))throw new Error('Identificador de arquivo inválido.');return n;}
function parseRanges(str,count){if(!String(str||'').trim())return[];return String(str).split(',').map(raw=>{const m=raw.trim().match(/^(\d+)(?:\s*-\s*(\d+))?$/);if(!m)throw new Error(`Intervalo inválido: ${raw}`);const a=Number(m[1]),b=Number(m[2]||m[1]);if(a<1||b<a||a>count)throw new Error(`Página inválida no intervalo: ${raw}`);const r=[];for(let i=a;i<=Math.min(b,count);i++)r.push(i-1);return r;});}
async function sendFile(res,file,name,extra=[],type='application/octet-stream',headers={}){try{const st=await fs.promises.stat(file);res.status(200).set({'Content-Type':type,'Content-Disposition':`attachment; filename="${String(name).replace(/"/g,'')}"`,'Content-Length':String(st.size),'Cache-Control':'no-store,max-age=0',...headers});const s=fs.createReadStream(file);s.on('close',()=>cleanup(file,...extra));s.pipe(res);}catch(e){cleanup(file,...extra);if(!res.headersSent)res.status(500).json({error:e.message});}}
function waitClose(s){return new Promise((r,j)=>{s.once('close',r);s.once('error',j);});}
async function makeZip(dir,zip){const o=fs.createWriteStream(zip),a=archiver('zip',{zlib:{level:6}}),done=waitClose(o);a.on('error',e=>o.destroy(e));a.pipe(o);for(const f of fs.readdirSync(dir).filter(Boolean))a.file(path.join(dir,f),{name:f});await a.finalize();await done;}
async function purge(){const cut=Date.now()-7200000;for(const dir of [UP,TMP]){let es=[];try{es=await fs.promises.readdir(dir,{withFileTypes:true});}catch(_){continue;}await Promise.all(es.map(async e=>{const f=path.join(dir,e.name);try{if((await fs.promises.stat(f)).mtimeMs<cut)await fs.promises.rm(f,{recursive:true,force:true});}catch(_){}}));}}
setInterval(()=>purge().catch(()=>{}),1800000).unref();purge().catch(()=>{});

app.post('/api/merge',upload.array('files',50),async(req,res)=>{const ins=(req.files||[]).map(f=>f.path);try{if(ins.length<2)throw new Error('Selecione pelo menos 2 PDFs.');req.files.forEach(validatePdf);const d=await PDFDocument.create();for(const f of req.files)(await d.copyPages(await PDFDocument.load(await fs.promises.readFile(f.path),{ignoreEncryption:true}),[...Array((await PDFDocument.load(await fs.promises.readFile(f.path),{ignoreEncryption:true})).getPageIndices())])).forEach(p=>d.addPage(p));const out=path.join(TMP,uuid()+'.pdf');await fs.promises.writeFile(out,await d.save());await sendFile(res,out,'unido.pdf',ins,'application/pdf');}catch(e){cleanup(...ins);if(!res.headersSent)res.status(500).json({error:e.message});}});
app.post('/api/split',upload.single('file'),async(req,res)=>{const input=req.file?.path;try{validatePdf(req.file);const src=await PDFDocument.load(await fs.promises.readFile(input),{ignoreEncryption:true}),rs=parseRanges(req.body.ranges,src.getPageCount()),groups=rs.length?rs:src.getPageIndices().map(i=>[i]);if(groups.length>100)throw new Error('Limite de 100 partes por operação.');const zip=path.join(TMP,uuid()+'.zip'),o=fs.createWriteStream(zip),a=archiver('zip',{zlib:{level:6}}),done=waitClose(o);a.on('error',e=>o.destroy(e));a.pipe(o);for(let i=0;i<groups.length;i++){const d=await PDFDocument.create();(await d.copyPages(src,groups[i])).forEach(p=>d.addPage(p));a.append(Buffer.from(await d.save()),{name:`parte_${i+1}.pdf`});}await a.finalize();await done;await sendFile(res,zip,'partes.zip',[input],'application/zip');}catch(e){cleanup(input);if(!res.headersSent)res.status(500).json({error:e.message});}});
app.post('/api/pages/edit',upload.single('file'),async(req,res)=>{const input=req.file?.path;try{validatePdf(req.file);const src=await PDFDocument.load(await fs.promises.readFile(input),{ignoreEncryption:true}),ops=JSON.parse(req.body.operations||'{}');let order=Array.isArray(ops.keepOrder)?ops.keepOrder.map(Number).map(n=>n-1):src.getPageIndices();const del=new Set((ops.delete||[]).map(Number).map(n=>n-1));if(order.some(i=>!Number.isInteger(i)||i<0||i>=src.getPageCount()))throw new Error('Ordem de páginas inválida.');order=order.filter(i=>!del.has(i));if(!order.length)throw new Error('O PDF final precisa ter pelo menos uma página.');const out=await PDFDocument.create();(await out.copyPages(src,order)).forEach((p,i)=>{const rot=Number(ops.rotations?.[order[i]+1]||0);if(rot)p.setRotation(degrees((p.getRotation().angle+rot)%360));out.addPage(p);});const f=path.join(TMP,uuid()+'.pdf');await fs.promises.writeFile(f,await out.save());await sendFile(res,f,'editado.pdf',[input],'application/pdf');}catch(e){cleanup(input);if(!res.headersSent)res.status(500).json({error:e.message});}});
app.post('/api/compress',upload.single('file'),async(req,res)=>{const input=req.file?.path,out=path.join(TMP,uuid()+'.pdf');try{validatePdf(req.file);const level=String(req.body.level||'ebook').toLowerCase();if(!['screen','ebook','printer','prepress','default'].includes(level))throw new Error('Nível de compressão inválido.');const orig=(await fs.promises.stat(input)).size;await run('gs',['-sDEVICE=pdfwrite','-dCompatibilityLevel=1.4',`-dPDFSETTINGS=/${level}`,'-dNOPAUSE','-dQUIET','-dBATCH',`-sOutputFile=${out}`,input],{timeout:240000});const size=(await fs.promises.stat(out)).size,pct=orig?Math.max(0,(1-size/orig)*100):0;await sendFile(res,out,'comprimido.pdf',[input],'application/pdf',{'X-Original-Size':orig,'X-Compressed-Size':size,'X-Compression-Percent':pct.toFixed(2)});}catch(e){cleanup(input,out);if(!res.headersSent)res.status(500).json({error:e.message});}});
app.post('/api/convert/images-to-pdf',upload.array('files',50),async(req,res)=>{const ins=(req.files||[]).map(f=>f.path);try{if(!req.files.length)throw new Error('Selecione pelo menos uma imagem.');const sharp=require('sharp'),d=await PDFDocument.create();for(const f of req.files){const b=await sharp(f.path).jpeg({quality:90,mozjpeg:true}).toBuffer(),img=await d.embedJpg(b),p=d.addPage([img.width,img.height]);p.drawImage(img,{x:0,y:0,width:img.width,height:img.height});}const out=path.join(TMP,uuid()+'.pdf');await fs.promises.writeFile(out,await d.save());await sendFile(res,out,'imagens.pdf',ins,'application/pdf');}catch(e){cleanup(...ins);if(!res.headersSent)res.status(500).json({error:e.message});}});
app.post('/api/convert/pdf-to-images',upload.single('file'),async(req,res)=>{const input=req.file?.path,dir=path.join(TMP,uuid());try{validatePdf(req.file);const fmt=String(req.body.format||'png').toLowerCase();if(!['png','jpg','jpeg'].includes(fmt))throw new Error('Formato de imagem inválido.');await fs.promises.mkdir(dir,{recursive:true});const flag=fmt==='png'?'-png':'-jpeg',args=[flag,'-r','150'];if(flag==='-jpeg')args.push('-jpegopt','quality=88');args.push(input,path.join(dir,'pagina'));await run('pdftocairo',args,{timeout:240000});if(!fs.readdirSync(dir).length)throw new Error('Nenhuma página foi convertida.');const zip=path.join(TMP,uuid()+'.zip');await makeZip(dir,zip);await sendFile(res,zip,'paginas.zip',[input,dir],'application/zip');}catch(e){cleanup(input,dir);if(!res.headersSent)res.status(500).json({error:e.message});}});
app.post('/api/convert/office',upload.single('file'),async(req,res)=>{const input=req.file?.path,dir=path.join(TMP,uuid());try{if(!req.file)throw new Error('Nenhum arquivo foi enviado.');const target=String(req.body.target||'pdf').toLowerCase();if(!['pdf','docx','pptx','xlsx','odt'].includes(target))throw new Error('Formato de saída inválido.');await fs.promises.mkdir(dir,{recursive:true});const profile=path.join(dir,'profile');const args=['--headless',`-env:UserInstallation=file://${profile}`,'--norestore','--nolockcheck','--nodefault','--nofirststartwizard'];if(path.extname(input).toLowerCase()==='.pdf'&&target!=='pdf')args.push('--infilter=writer_pdf_import');args.push('--convert-to',target,'--outdir',dir,input);await run('soffice',args,{timeout:240000});const files=fs.readdirSync(dir).filter(f=>f!=='profile'&&!f.startsWith('.~lock')).filter(f=>{try{return fs.statSync(path.join(dir,f)).isFile();}catch(_){return false;}});if(!files.length)throw new Error('A conversão não gerou saída.');const out=path.join(dir,files[0]);await sendFile(res,out,files[0],[input,dir],target==='pdf'?'application/pdf':'application/octet-stream');}catch(e){cleanup(input,dir);if(!res.headersSent)res.status(500).json({error:e.message});}});
app.post('/api/inspect',upload.single('file'),async(req,res)=>{const input=req.file?.path;let dir=null,name=null;try{validatePdf(req.file);const bytes=await fs.promises.readFile(input),src=await PDFDocument.load(bytes,{ignoreEncryption:true}),count=src.getPageCount(),sizes=src.getPages().map(p=>p.getSize()),id=uuid();name=id+'.pdf';await fs.promises.copyFile(input,path.join(UP,name));dir=path.join(TMP,'thumbs_'+id);await fs.promises.mkdir(dir,{recursive:true});await run('pdftocairo',['-jpeg','-jpegopt','quality=76','-scale-to','1100',input,path.join(dir,'page')],{timeout:240000});const files=fs.readdirSync(dir).filter(f=>/^page-\d+\.jpg$/i.test(f)).sort((a,b)=>Number(a.match(/\d+/)[0])-Number(b.match(/\d+/)[0])),thumbs=files.map(f=>'data:image/jpeg;base64,'+fs.readFileSync(path.join(dir,f)).toString('base64')),boxes=[];try{const bbox=path.join(dir,'bbox.html');await run('pdftotext',['-bbox','-enc','UTF-8',input,bbox],{timeout:120000});const html=await fs.promises.readFile(bbox,'utf8'),pages=[...html.matchAll(/<page[^>]*>([\s\S]*?)<\/page>/gi)];pages.forEach((m,pi)=>{const scale=Math.min(1100/(sizes[pi]?.width||612),1100/(sizes[pi]?.height||792));[...m[1].matchAll(/<word[^>]*xMin="([0-9.]+)"[^>]*yMin="([0-9.]+)"[^>]*xMax="([0-9.]+)"[^>]*yMax="([0-9.]+)"[^>]*>([\s\S]*?)<\/word>/gi)].forEach((w,wi)=>{const text=w[5].replace(/<[^>]+>/g,'').trim();if(!text)return;const x=+w[1],y=+w[2],ww=Math.max(1,+w[3]-x),hh=Math.max(1,+w[4]-y);boxes.push({id:`p${pi+1}-w${wi+1}`,page:pi+1,x:x*scale,y:y*scale,width:ww*scale,height:hh*scale,pdfX:x,pdfY:y,pdfWidth:ww,pdfHeight:hh,text,fontSize:Math.max(6,hh*scale)});});});}catch(_){}res.json({fileId:name,pageCount:count,pageSizes:sizes,thumbnails:thumbs,textBoxes:boxes});}catch(e){cleanup(name?path.join(UP,name):null);if(!res.headersSent)res.status(500).json({error:e.message});}finally{cleanup(input,dir);}});
app.get('/api/preview/:id/:page',async(req,res)=>{let dir=null;try{const id=safeFileId(req.params.id),page=Number(req.params.page),pdf=path.join(UP,id);if(!Number.isInteger(page)||page<1)return res.status(400).send('Página inválida.');if(!fs.existsSync(pdf))return res.status(404).send('PDF não encontrado.');dir=path.join(TMP,uuid());await fs.promises.mkdir(dir,{recursive:true});const p=path.join(dir,'page');await run('pdftocairo',['-f',String(page),'-l',String(page),'-singlefile','-png','-scale-to','1600',pdf,p],{timeout:120000});if(!fs.existsSync(p+'.png'))return res.status(404).send('Página não encontrada.');res.type('png').sendFile(path.resolve(p+'.png'),()=>cleanup(dir));}catch(e){cleanup(dir);if(!res.headersSent)res.status(500).send(e.message);}});
app.use('/uploads',express.static(UP,{index:false,dotfiles:'deny',maxAge:'5m'}));
app.post('/api/edit/annotate',upload.single('image'),async(req,res)=>{try{const file=safeFileId(req.body.fileId),filePath=path.join(UP,file);if(!fs.existsSync(filePath))return res.status(400).json({error:'Arquivo não encontrado. Reenvie o PDF.'});const anns=JSON.parse(req.body.annotations||'[]');const mupdf=await import('mupdf'),doc=mupdf.Document.openDocument(await fs.promises.readFile(filePath),'application/pdf'),pdf=doc.asPDF(),redactedPages=new Set();try{for(const a of anns){if(!a||!String(a.id||'').startsWith('p'))continue;const i=Number(a.page)-1,x=Number(a.pdfX??a.x),y=Number(a.pdfY??a.y),w=Number(a.pdfWidth??a.width),h=Number(a.pdfHeight??a.height);if(!Number.isInteger(i)||i<0||i>=pdf.countPages()||![x,y,w,h].every(Number.isFinite)||w<=0||h<=0)continue;const p=pdf.loadPage(i),b=p.getBounds(),r=p.createAnnotation('Redact');r.setRect([Math.max(b[0],x-1.5),Math.max(b[1],y-1.5),Math.min(b[2],x+w+1.5),Math.min(b[3],y+h+1.5)]);r.update();redactedPages.add(i);p.destroy();}for(const i of redactedPages){const p=pdf.loadPage(i);p.applyRedactions(false,mupdf.PDFPage.REDACT_IMAGE_PIXELS,mupdf.PDFPage.REDACT_LINE_ART_REMOVE_IF_COVERED,mupdf.PDFPage.REDACT_TEXT_REMOVE);p.destroy();}var red=Buffer.from(pdf.saveToBuffer('garbage=4,compress=yes').asUint8Array());}finally{doc.destroy();}const out=await PDFDocument.load(red,{ignoreEncryption:true}),font=await out.embedFont(StandardFonts.Helvetica);for(const a of anns){if(!a||!String(a.id||'').startsWith('p'))continue;const p=out.getPage(Number(a.page)-1);if(!p)continue;const ph=p.getHeight(),x=Number(a.pdfX??a.x)||0,y=Number(a.pdfY??a.y)||0,w=Number(a.pdfWidth??a.width)||20,h=Number(a.pdfHeight??a.height)||12,size=Math.max(4,Math.min(Number(a.fontSize)||h,h));p.drawRectangle({x:Math.max(0,x-1.5),y:Math.max(0,ph-y-h-1.5),width:w+3,height:h+3,color:rgb(1,1,1),borderWidth:0});if(a.deleted!==true&&String(a.text||''))p.drawText(String(a.text),{x,y:ph-y-size,size,font,color:rgb(.1,.1,.1),maxWidth:Math.max(10,w)});}const outPath=path.join(TMP,uuid()+'.pdf');await fs.promises.writeFile(outPath,await out.save({useObjectStreams:false}));await sendFile(res,outPath,'editado.pdf',[],'application/pdf');}catch(e){if(!res.headersSent)res.status(500).json({error:e.message});}});
app.get('/api/health',(req,res)=>res.json({ok:true,uptime:Math.round(process.uptime()),timestamp:new Date().toISOString()}));
app.use((err,req,res,next)=>{cleanup(req.file?.path,...(req.files||[]).map(f=>f.path));if(err instanceof multer.MulterError)return res.status(413).json({error:err.code==='LIMIT_FILE_SIZE'?'Arquivo maior que 200 MB.':`Upload inválido: ${err.message}`});if(err)return res.status(400).json({error:err.message||'Erro ao processar a solicitação.'});next();});
app.listen(PORT,()=>console.log(`PDFTools rodando na porta ${PORT}`));
