const express = require('express');
const multer = require('multer');
const cors = require('cors');
const path = require('path');
const fs = require('fs');
const { v4: uuid } = require('uuid');
const archiver = require('archiver');
const { execFile } = require('child_process');
const { PDFDocument, degrees, rgb, StandardFonts } = require('pdf-lib');

const app = express();
const PORT = process.env.PORT || 10000;
const UP = path.join(__dirname, 'uploads');
const TMP = path.join(__dirname, 'tmp');
[UP, TMP].forEach(d => fs.mkdirSync(d, { recursive: true }));
app.disable('x-powered-by'); app.set('trust proxy', 1);
app.use(cors()); app.use(express.static(path.join(__dirname, 'public'))); app.use(express.json({limit:'2mb'}));
const ALLOWED_EXT=new Set(['.pdf','.doc','.docx','.xls','.xlsx','.ppt','.pptx','.odt','.jpg','.jpeg','.png','.webp','.gif','.bmp','.tif','.tiff']);
const upload=multer({storage:multer.diskStorage({destination:(r,f,c)=>c(null,UP),filename:(r,f,c)=>c(null,uuid()+path.extname(f.originalname||'').toLowerCase())}),limits:{fileSize:200*1024*1024,files:50,fields:20,parts:70},fileFilter:(r,f,c)=>ALLOWED_EXT.has(path.extname(f.originalname||'').toLowerCase())?c(null,true):c(new Error('Tipo de arquivo não permitido.'))});
function run(cmd,args,o={}){return new Promise((resolve,reject)=>execFile(cmd,args,{maxBuffer:20*1024*1024,timeout:o.timeout||180000,windowsHide:true},(e,out,err)=>e?reject(new Error(String(err||e.message).slice(0,2500))):resolve(out)));}
function cleanup(...f){f.filter(Boolean).forEach(x=>fs.rm(x,{recursive:true,force:true},()=>{}));}
function validatePdf(f){if(!f)throw new Error('Nenhum arquivo foi enviado.');if(path.extname(f.originalname||'').toLowerCase()!=='.pdf')throw new Error('Este recurso aceita somente PDF.');}
function safeFileId(id){const n=path.basename(String(id||''));if(!/^[0-9a-f-]{36}\.pdf$/i.test(n))throw new Error('Identificador de arquivo inválido.');return n;}
function parseRanges(s,count){if(!String(s||'').trim())return[];return String(s).split(',').map(raw=>{const m=raw.trim().match(/^(\d+)(?:\s*-\s*(\d+))?$/);if(!m)throw new Error(`Intervalo inválido: ${raw}`);const a=+m[1],b=+(m[2]||m[1]);if(a<1||b<a||a>count)throw new Error(`Página inválida no intervalo: ${raw}`);const r=[];for(let i=a;i<=Math.min(b,count);i++)r.push(i-1);return r;});}
async function sendFile(res,file,name,extra=[],type='application/octet-stream',headers={}){try{const st=await fs.promises.stat(file);res.status(200).set({'Content-Type':type,'Content-Disposition':`attachment; filename="${String(name).replace(/"/g,'')}"`,'Content-Length':String(st.size),'Cache-Control':'no-store,max-age=0',...headers});const s=fs.createReadStream(file);s.on('close',()=>cleanup(file,...extra));s.pipe(res);}catch(e){cleanup(file,...extra);if(!res.headersSent)res.status(500).json({error:e.message});}}
function waitClose(s){return new Promise((r,j)=>{s.once('close',r);s.once('error',j);});}
async function zipDir(dir,zip){const o=fs.createWriteStream(zip),a=archiver('zip',{zlib:{level:6}}),done=waitClose(o);a.on('error',e=>o.destroy(e));a.pipe(o);for(const f of fs.readdirSync(dir).filter(Boolean))a.file(path.join(dir,f),{name:f});await a.finalize();await done;}

app.post('/api/merge',upload.array('files',50),async(req,res)=>{const ins=(req.files||[]).map(f=>f.path);try{if(ins.length<2)throw new Error('Selecione pelo menos 2 PDFs.');req.files.forEach(validatePdf);const d=await PDFDocument.create();for(const f of req.files){const s=await PDFDocument.load(await fs.promises.readFile(f.path),{ignoreEncryption:true});(await d.copyPages(s,s.getPageIndices())).forEach(p=>d.addPage(p));}const o=path.join(TMP,uuid()+'.pdf');await fs.promises.writeFile(o,await d.save());await sendFile(res,o,'unido.pdf',ins,'application/pdf');}catch(e){cleanup(...ins);if(!res.headersSent)res.status(500).json({error:e.message});}});
app.post('/api/split',upload.single('file'),async(req,res)=>{const input=req.file?.path;try{validatePdf(req.file);const s=await PDFDocument.load(await fs.promises.readFile(input),{ignoreEncryption:true}),r=parseRanges(req.body.ranges,s.getPageCount()),g=r.length?r:s.getPageIndices().map(i=>[i]);const z=path.join(TMP,uuid()+'.zip'),o=fs.createWriteStream(z),a=archiver('zip',{zlib:{level:6}}),done=waitClose(o);a.on('error',e=>o.destroy(e));a.pipe(o);for(let i=0;i<g.length;i++){const d=await PDFDocument.create();(await d.copyPages(s,g[i])).forEach(p=>d.addPage(p));a.append(Buffer.from(await d.save()),{name:`parte_${i+1}.pdf`});}await a.finalize();await done;await sendFile(res,z,'partes.zip',[input],'application/zip');}catch(e){cleanup(input);if(!res.headersSent)res.status(500).json({error:e.message});}});
app.post('/api/pages/edit',upload.single('file'),async(req,res)=>{const input=req.file?.path;try{validatePdf(req.file);const s=await PDFDocument.load(await fs.promises.readFile(input),{ignoreEncryption:true}),ops=JSON.parse(req.body.operations||'{}');let order=(ops.keepOrder||s.getPageIndices().map(i=>i+1)).map(Number).map(n=>n-1);const del=new Set((ops.delete||[]).map(Number).map(n=>n-1));order=order.filter(i=>!del.has(i));if(!order.length)throw new Error('O PDF final precisa ter pelo menos uma página.');const d=await PDFDocument.create();(await d.copyPages(s,order)).forEach((p,i)=>{const rot=+(ops.rotations?.[order[i]+1]||0);if(rot)p.setRotation(degrees((p.getRotation().angle+rot)%360));d.addPage(p);});const o=path.join(TMP,uuid()+'.pdf');await fs.promises.writeFile(o,await d.save());await sendFile(res,o,'editado.pdf',[input],'application/pdf');}catch(e){cleanup(input);if(!res.headersSent)res.status(500).json({error:e.message});}});
app.post('/api/compress',upload.single('file'),async(req,res)=>{const input=req.file?.path,o=path.join(TMP,uuid()+'.pdf');try{validatePdf(req.file);const level=String(req.body.level||'ebook').toLowerCase(),orig=(await fs.promises.stat(input)).size;if(!['screen','ebook','printer','prepress','default'].includes(level))throw new Error('Nível de compressão inválido.');await run('gs',['-sDEVICE=pdfwrite','-dCompatibilityLevel=1.4',`-dPDFSETTINGS=/${level}`,'-dNOPAUSE','-dQUIET','-dBATCH',`-sOutputFile=${o}`,input],{timeout:240000});const size=(await fs.promises.stat(o)).size,pct=orig?Math.max(0,(1-size/orig)*100):0;await sendFile(res,o,'comprimido.pdf',[input],'application/pdf',{'X-Original-Size':orig,'X-Compressed-Size':size,'X-Compression-Percent':pct.toFixed(2)});}catch(e){cleanup(input,o);if(!res.headersSent)res.status(500).json({error:e.message});}});
app.post('/api/convert/images-to-pdf',upload.array('files',50),async(req,res)=>{const ins=(req.files||[]).map(f=>f.path);try{const sharp=require('sharp'),d=await PDFDocument.create();for(const f of req.files){const b=await sharp(f.path).jpeg({quality:90,mozjpeg:true}).toBuffer(),img=await d.embedJpg(b),p=d.addPage([img.width,img.height]);p.drawImage(img,{x:0,y:0,width:img.width,height:img.height});}const o=path.join(TMP,uuid()+'.pdf');await fs.promises.writeFile(o,await d.save());await sendFile(res,o,'imagens.pdf',ins,'application/pdf');}catch(e){cleanup(...ins);if(!res.headersSent)res.status(500).json({error:e.message});}});
app.post('/api/convert/pdf-to-images',upload.single('file'),async(req,res)=>{const input=req.file?.path,dir=path.join(TMP,uuid());try{validatePdf(req.file);const fmt=String(req.body.format||'png').toLowerCase();if(!['png','jpg','jpeg'].includes(fmt))throw new Error('Formato de imagem inválido.');await fs.promises.mkdir(dir,{recursive:true});const flag=fmt==='png'?'-png':'-jpeg',args=[flag,'-r','150'];if(flag==='-jpeg')args.push('-jpegopt','quality=88');args.push(input,path.join(dir,'pagina'));await run('pdftocairo',args,{timeout:240000});const z=path.join(TMP,uuid()+'.zip');await zipDir(dir,z);await sendFile(res,z,'paginas.zip',[input,dir],'application/zip');}catch(e){cleanup(input,dir);if(!res.headersSent)res.status(500).json({error:e.message});}});
app.post('/api/convert/office',upload.single('file'),async(req,res)=>{const input=req.file?.path,dir=path.join(TMP,uuid());try{if(!req.file)throw new Error('Nenhum arquivo foi enviado.');const target=String(req.body.target||'pdf').toLowerCase();await fs.promises.mkdir(dir,{recursive:true});const profile=path.join(dir,'lo-profile'),args=['--headless',`-env:UserInstallation=file://${profile}`,'--norestore','--nolockcheck','--nodefault','--nofirststartwizard'];if(path.extname(input).toLowerCase()==='.pdf'&&target!=='pdf')args.push('--infilter=writer_pdf_import');args.push('--convert-to',target,'--outdir',dir,input);await run('soffice',args,{timeout:240000});const files=fs.readdirSync(dir).filter(f=>f!=='lo-profile'&&!f.startsWith('.~lock')).filter(f=>{try{return fs.statSync(path.join(dir,f)).isFile();}catch(_){return false;}});if(!files.length)throw new Error('A conversão não gerou saída.');await sendFile(res,path.join(dir,files[0]),files[0],[input,dir],target==='pdf'?'application/pdf':'application/octet-stream');}catch(e){cleanup(input,dir);if(!res.headersSent)res.status(500).json({error:e.message});}});
app.post('/api/inspect',upload.single('file'),async(req,res)=>{const input=req.file?.path;let dir=null,name=null;try{validatePdf(req.file);const b=await fs.promises.readFile(input),s=await PDFDocument.load(b,{ignoreEncryption:true}),count=s.getPageCount(),sizes=s.getPages().map(p=>p.getSize()),id=uuid();name=id+'.pdf';await fs.promises.copyFile(input,path.join(UP,name));dir=path.join(TMP,'thumbs_'+id);await fs.promises.mkdir(dir,{recursive:true});await run('pdftocairo',['-jpeg','-jpegopt','quality=76','-scale-to','1100',input,path.join(dir,'page')],{timeout:240000});const fs2=fs.readdirSync(dir).filter(f=>/^page-\d+\.jpg$/i.test(f)).sort((a,b)=>+a.match(/\d+/)[0]-+b.match(/\d+/)[0]),thumbs=fs2.map(f=>'data:image/jpeg;base64,'+fs.readFileSync(path.join(dir,f)).toString('base64'));res.json({fileId:name,pageCount:count,pageSizes:sizes,thumbnails:thumbs,textBoxes:[]});}catch(e){cleanup(name?path.join(UP,name):null);if(!res.headersSent)res.status(500).json({error:e.message});}finally{cleanup(input,dir);}});
app.get('/api/preview/:id/:page',async(req,res)=>{let dir=null;try{const id=safeFileId(req.params.id),page=+req.params.page,pdf=path.join(UP,id);if(!fs.existsSync(pdf))return res.status(404).send('PDF não encontrado.');dir=path.join(TMP,uuid());await fs.promises.mkdir(dir,{recursive:true});const p=path.join(dir,'page');await run('pdftocairo',['-f',String(page),'-l',String(page),'-singlefile','-png','-scale-to','1600',pdf,p],{timeout:120000});res.type('png').sendFile(path.resolve(p+'.png'),()=>cleanup(dir));}catch(e){cleanup(dir);if(!res.headersSent)res.status(500).send(e.message);}});
app.use('/uploads',express.static(UP,{index:false,dotfiles:'deny',maxAge:'5m'}));
app.post('/api/edit/annotate',upload.single('image'),async(req,res)=>{try{const id=safeFileId(req.body.fileId),file=path.join(UP,id),anns=JSON.parse(req.body.annotations||'[]');if(!fs.existsSync(file))return res.status(400).json({error:'Arquivo não encontrado. Reenvie o PDF.'});const mupdf=await import('mupdf'),doc=mupdf.Document.openDocument(await fs.promises.readFile(file),'application/pdf'),pdf=doc.asPDF();try{for(const a of anns){if(!a||!String(a.id||'').startsWith('p'))continue;const i=+a.page-1,x=+(a.pdfX??a.x),y=+(a.pdfY??a.y),w=+(a.pdfWidth??a.width),h=+(a.pdfHeight??a.height);if(i<0||i>=pdf.countPages()||![x,y,w,h].every(Number.isFinite))continue;const p=pdf.loadPage(i),r=p.createAnnotation('Redact');r.setRect([x,y,x+w,y+h]);r.update();p.applyRedactions(false,mupdf.PDFPage.REDACT_IMAGE_PIXELS,mupdf.PDFPage.REDACT_LINE_ART_REMOVE_IF_COVERED,mupdf.PDFPage.REDACT_TEXT_REMOVE);p.destroy();}var red=Buffer.from(pdf.saveToBuffer('garbage=4,compress=yes').asUint8Array());}finally{doc.destroy();}const out=await PDFDocument.load(red,{ignoreEncryption:true}),font=await out.embedFont(StandardFonts.Helvetica);for(const a of anns){if(a.deleted===true||!a.text)continue;const p=out.getPage(+a.page-1);if(p)p.drawText(String(a.text),{x:+a.pdfX||0,y:p.getHeight()-(+a.pdfY||0)-(+a.fontSize||12),size:+a.fontSize||12,font,color:rgb(.1,.1,.1)});}const o=path.join(TMP,uuid()+'.pdf');await fs.promises.writeFile(o,await out.save());await sendFile(res,o,'editado.pdf',[],'application/pdf');}catch(e){if(!res.headersSent)res.status(500).json({error:e.message});}});
app.get('/api/health',(req,res)=>res.json({ok:true,uptime:Math.round(process.uptime()),timestamp:new Date().toISOString()}));
app.use((err,req,res,next)=>{cleanup(req.file?.path,...(req.files||[]).map(f=>f.path));if(err instanceof multer.MulterError)return res.status(413).json({error:err.code==='LIMIT_FILE_SIZE'?'Arquivo maior que 200 MB.':err.message});if(err)return res.status(400).json({error:err.message||'Erro ao processar a solicitação.'});next();});
app.listen(PORT,()=>console.log(`PDFTools rodando na porta ${PORT}`));
